INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1000, 'Books');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (2000, 'Movies');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (3000, 'Tools');

INSERT INTO SUPPLIER (ID, NAME) VALUES (1000, 'Suma');
INSERT INTO SUPPLIER (ID, NAME) VALUES (2000, 'Warner');
INSERT INTO SUPPLIER (ID, NAME) VALUES (3000, 'Tramontina');

INSERT INTO PRODUCT (ID, NAME, AVAILABLE_QUANTITY, FK_SUPPLIER, FK_CATEGORY, CREATED_AT) VALUES (1000, 'Joyland', 10, 1000, 1000, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (ID, NAME, AVAILABLE_QUANTITY, FK_SUPPLIER, FK_CATEGORY, CREATED_AT) VALUES (2000, 'Chuck', 5, 2000, 2000, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (ID, NAME, AVAILABLE_QUANTITY, FK_SUPPLIER, FK_CATEGORY, CREATED_AT) VALUES (3000, 'Pliers', 20, 3000, 3000, CURRENT_TIMESTAMP);