INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1, 'Books');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (2, 'Movies');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (3, 'Tools');

INSERT INTO SUPPLIER (ID, NAME) VALUES (1, 'Suma');
INSERT INTO SUPPLIER (ID, NAME) VALUES (2, 'Warner');
INSERT INTO SUPPLIER (ID, NAME) VALUES (3, 'Tramontina');

INSERT INTO PRODUCT (ID, NAME, AVAILABLE_QUANTITY, FK_SUPPLIER, FK_CATEGORY) VALUES (1, 'Joyland', 10, 1, 1);

INSERT INTO PRODUCT (ID, NAME, AVAILABLE_QUANTITY, FK_SUPPLIER, FK_CATEGORY) VALUES (2, 'Chuck', 5, 2, 2);

INSERT INTO PRODUCT (ID, NAME, AVAILABLE_QUANTITY, FK_SUPPLIER, FK_CATEGORY) VALUES (3, 'Pliers', 20, 3, 3);